# @package _global_

# укажите здесь конфигурацию по умолчанию
# порядок дефолтов определяет порядок переопределения конфигов
defaults:
  - _self_
  - data: cs_datamodule
  - model: base_det
  - callbacks: default
  - logger: tensorboard # установите логгер здесь или используйте командную строку (например, `python train.py logger=tensorboard`)
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

  # конфиги экспериментов позволяют версионировать конкретные гиперпараметры
  # например, лучшие гиперпараметры для данной модели и датамодуля
  - experiment: null

  # опциональный локальный конфиг для машина/пользователь-специфичных настроек
  # опционально, так как не должен существовать и исключен из контроля версий
  - optional local: default

  # конфиг для отладки (включить командной строкой, например, `python train.py debug=default)
  - debug: null

# название задачи, определяет путь выходной директории
task_name: "train"
experiment_name: "full_img512_yolo8n"
# теги для идентификации ваших экспериментов
# вы можете переопределить это в конфигах экспериментов
# переопределите из командной строки с помощью `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]

# установите False, чтобы пропустить обучение модели
train: True

# оцените на тестовом наборе, используя лучшие веса модели, полученные во время обучения
# lightning выбирает лучшие веса на основе метрики, указанной в callback'е контрольной точки
test: True

# просто предоставьте путь контрольной точки для возобновления обучения
ckpt_path: null

# семя для генераторов случайных чисел в pytorch, numpy и python.random
seed: null

# установите точность matmul для GPU Tensor Core; используйте null, чтобы сохранить PyTorch по умолчанию
matmul_precision: "medium"
